name = "et-juicy233"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改

id = "326ad100064f4ecf9a3e3eab9a3614dc"				#KV数据库id





